spring:
  application:
    name: group-wise
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        highlight_sql: true        # SQL 하이라이트 추가
        use_sql_comments: true     # JPQL 쿼리 주석 추가

logging:
  level:
    root: warn
    org:
      springframework:
        web: debug        # 웹 요청/응답 로깅
        security: debug   # 스프링 시큐리티 로깅
        jdbc: debug       # JDBC 로깅
      hibernate:
        SQL: debug       # 실행되는 모든 SQL문 출력
        orm.jdbc.bind: trace  # 바인딩 파라미터 출력
    jdbc:
        connection: debug
    com.zaxxer.hikari: DEBUG


jwt:
  secret: 07c32ce0bb274e139540f656d892f0e6