spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME_PROD}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10     # 최대 커넥션 수
      minimum-idle: 5           # 최소 유휴 커넥션 수
      idle-timeout: 600000      # 유휴 연결 제거 전 대기 시간 (10분)
      max-lifetime: 1800000     # 연결 최대 수명 (30분)
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true  # 마이그레이션 전 검증
    out-of-order: false  # 마이그레이션 스크립트 순서 강제
    clean-disabled: true  # 데이터베이스 초기화 방지

logging:
  level:
    root: warn
    org:
      springframework:
        web: info
        security: info
        jdbc: warn
      hibernate:
        SQL: info  # SQL 쿼리 로그
    jdbc:
      connection: warn
    com.zaxxer.hikari: info
jwt:
  secret: ${JWT_SECRET_KEY}