spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME_PROD}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        highlight_sql: true        # SQL 하이라이트 추가
        use_sql_comments: true     # JPQL 쿼리 주석 추가
        default_batch_fetch_size: 100
    #        javax.persistence.schema-validation.before-flyway: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true  # 마이그레이션 전 검증
    out-of-order: false  # 마이그레이션 스크립트 순서 강제
    clean-disabled: true  # 데이터베이스 초기화 방지

logging:
  level:
    root: warn
    org:
      springframework:
        web: debug        # 웹 요청/응답 로깅
        security: debug   # 스프링 시큐리티 로깅
        jdbc: debug       # JDBC 로깅
      hibernate:
        SQL: debug       # 실행되는 모든 SQL문 출력
        orm.jdbc.bind: trace  # 바인딩 파라미터 출력
    jdbc:
      connection: debug
    com.zaxxer.hikari: DEBUG
jwt:
  secret: ${JWT_SECRET_KEY}