name: Deploy to EC2

on:
  push:
    branches:
      [main , group-wise-*]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: SSH로 EC2에 접속하기
            uses: appleboy/ssh-action@v1
            with:
              host: ${{ secrets.EC2_HOST }}
              username: ${{ secrets.EC2_USERNAME }}
              key: ${{ secrets.EC2_PRIVATE_KEY }}
              script: |
                # 로그 디렉토리 생성
                mkdir -p /home/ubuntu/group-wise/logs
            
                cd /home/ubuntu/group-wise
                git pull origin main
                ./gradlew clean build
                
                # 기존 프로세스 종료
                sudo fuser -k -n tcp 8080 || true
                
                # 환경변수 설정
                export DB_HOST=${{ secrets.DB_HOST }}
                export DB_NAME_PROD=${{ secrets.DB_NAME_PROD }}
                export DB_USERNAME=${{ secrets.DB_USERNAME }}
                export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
                export JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
                
                # 애플리케이션 실행 (로그 디렉토리에 날짜별 로그 저장)
                nohup java -jar build/libs/*SNAPSHOT.jar > ./logs/application-$(date +%Y%m%d).log 2>&1 &
                
                # 간단한 헬스 체크
                sleep 20
                echo "Checking if application is running..."
                ps aux | grep java